# Generated by Django 4.2.2 on 2023-06-09 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Listing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="property",
            name="date_listed",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="property",
            name="location",
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name="property",
            name="price",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="property",
            name="sqft",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
