# Generated by Django 4.2.2 on 2023-06-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Listing", "0002_property_bathrooms_property_bedrooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="image",
            field=models.ImageField(
                default="images not available", upload_to="property_images"
            ),
            preserve_default=False,
        ),
    ]
